name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: HTML tester
      id: html-tester
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip install pytest bs4 cssutils
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HTML-TESTER_RESULTS: "${{steps.html-tester.outputs.result}}"
      with:
        runners: html-tester
